### ISSUE TITLE
Would be nice some tooltip in menu

### ISSUE THREAD

**Issue by joaosilva-lp** [nash-md/meow#1]
Hi, great program, really simple and intuitive. I suggest you the option to delete sales (can't find it), and also a tooltip on menu hover.
Greatings,
João

**Comment by nash-md** [comment]
Hi João, thanks for the feedback. Whenever you drag a card (opportunity) there should be a trash area on the top right. Was this what you mean with delete sales? Would it be better to have a delete delete option on the opportunity detail view?

I will add tooltips, I keep this open until they are implemented
