### ISSUE TITLE
BASE_URL parameter is not set causing the container to continously restart

### ISSUE THREAD

**Issue by nikomaxos** [nash-md/meow#2]
While proceeding to normal docker installation on Linux, the db container is running without any issue, but the app container is reporting an error that is causing a reboot loop. 
OS: Ubuntu 23.04 X64
Docker Version: Standalone 20.10.24 

Pasting the log below:

` 
> meow@0.2 start
> npm run build && node build/worker.js
> meow@0.2 build
> rm -rf build && npx tsc --build tsconfig.json
Setting metadata for entity Team
Setting metadata for entity NewTeam
Setting metadata for entity User
Setting metadata for entity NewUser
Setting metadata for entity Board
Setting metadata for entity NewBoard
Setting metadata for entity Lane
Setting metadata for entity NewLane
Setting metadata for entity Card
Setting metadata for entity NewCard
Setting metadata for entity Schema
Setting metadata for entity NewSchema
Setting metadata for entity ForecastEvent
Setting metadata for entity NewForecastEvent
Setting metadata for entity CardEvent
Setting metadata for entity NewCardEvent
Setting metadata for entity Account
Setting metadata for entity NewAccount
Setting metadata for entity AccountEvent
Setting metadata for entity NewAccountEvent
2023/11/01 11:20AM 50 pid=69 hostname=31c7e8e5fe30 name=meow-backend-service msg=env variable BASE_URL is not set, exiting worker ...`

**Comment by nash-md** [comment]
@nikomaxos thanks for reporting the bug. The issue should be fixed, `BASE_URL` is actually not used, is for the Google login we use on the hosted version.

I tried it with Docker and it worked for me,  please make sure you to update your sources and build the docker container again with `docker-compose up --build`. There was another issue and the Typescript compiler failed, it is fixed now too.

**Comment by nikomaxos** [comment]
> @nikomaxos thanks for reporting the bug. The issue should be fixed, `BASE_URL` is actually not used, is for the Google login we use on the hosted version.
> 
> I tried it with Docker and it worked for me, please make sure you to update your sources and build the docker container again with `docker-compose up --build`. There was another issue and the Typescript compiler failed, it is fixed now too.

Thanks for your feedback, now I received:

sudo docker-compose build
[+] Building 75.6s (1/1) FINISHED                                               
 => ERROR [internal] booting buildkit                                     75.6s
 => => pulling image moby/buildkit:buildx-stable-1                        60.4s
 => => creating container buildx_buildkit_default                         15.2s
------
 > [internal] booting buildkit:
#0 75.62 time="2023-11-01T15:46:37Z" level=warning msg="using host network as the defaultime="2023-11-01T15:46:37Z" level=warning msg="using host network as the default"
#0 75.62 time="2023-11-01T15:46:37Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 75.62 dtime="2023-11-01T15:46:37Z" level=info msg="found 1 workers, default=\"xirn50wunozyx0xtotibluqvx\""
#0 75.62 `time="2023-11-01T15:46:37Z" level=warning msg="currently, only the default worker can be used."
#0 75.62 \time="2023-11-01T15:46:37Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 75.62 time="2023-11-01T15:46:37Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 75.62 time="2023-11-01T15:46:37Z" level=warning msg="currently, only the default worker can be used."
#0 75.62 time="2023-11-01T15:46:37Z" level=warning msg="currently, only the default worker can be used."
#0 75.62 
------
http: invalid Host header

**Comment by nash-md** [comment]
When you execute `sudo docker-compose build`, the build process fails during the initialization of BuildKit. The log indicates an issue with the network configuration and the absence of the containerd socket.

Can you please restart the Docker service (sudo systemctl restart docker) and try the build command again. If it still dos not work can you share the complete build log?

**Comment by nikomaxos** [comment]
Nope, it didnt work, build log below:

` 
> 
~/meow$ sudo docker-compose build
[+] Building 14.7s (1/1) FINISHED                                                                                                                  
 => ERROR [internal] booting buildkit                                                                                                        14.7s
 => => starting container buildx_buildkit_default                                                                                            14.7s
 > [internal] booting buildkit:
#0 14.71 time="2023-11-02T08:07:25Z" level=warning msg="using host network as the defaultime="2023-11-02T08:07:25Z" level=warning msg="using host network as the default"
#0 14.71 time="2023-11-02T08:07:26Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 14.71 dtime="2023-11-02T08:07:26Z" level=info msg="found 1 workers, default=\"nl69o8ek1vi8o1ljvjjv8azrb\""
#0 14.71 `time="2023-11-02T08:07:26Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 \time="2023-11-02T08:07:26Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 14.71 =time="2023time="2023-11-02T08:07:26Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 14.71 time="2023-11-02T08:07:26Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 time="2023-11-02T08:07:26Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 time="2023-11-02T08:09:54Z" level=info msg="stopping server"
#0 14.71 buildkitd: context canctime="2023-11-02T08:09:54Z" level=info msg="stopping server"
#0 14.71 time="2023-11-02T08:09:59Z" time="2023-11-02T08:09:59Z" level=info msg="auto snapshotter: using overlayfs"
#0 14.71 time="2023-11-02T08:09:59Z" level=info msg="found worker \"nl69o8ek1vi8o1ljvjjv8aztime="2023-11-02T08:09:59Z" level=info msg="found worker \"nl69o8ek1vi8o1ljvjjv8azrb\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:a7533adf3326 org.mobyproject.buildkit.worker.network:host org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/386]"
#0 14.71 time="2023-11-02T08:09:59Z" level=info msg="found 1 workers, default=\"nl69o8ek1vi8o1ljvjjv8azrb\""
#0 14.71 `time="2023-11-02T08:09time="2023-11-02T08:09:59Z" level=info msg="found 1 workers, default=\"nl69o8ek1vi8o1ljvjjv8azrb\""
#0 14.71 time="2023-11-02T08:09:59Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 14.71 time="2023-11-02T08:09:59Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 14.71 buildkitd: context canceled
#0 14.71 Otime="2023-11-02T08:14:37buildkitd: context canceled
#0 14.71 time="2023-11-02T08:14:37Z" level=warning msg="using host network as the defaultime="2023-11-02T08:14:37Z" level=warning msg="using host network as the default"
#0 14.71 time="2023-11-02T08:14:37Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 14.71 dtime="2023-11-02T08:14:37Z" level=info msg="found 1 workers, default=\"nl69o8ek1vi8o1ljvjjv8azrb\""
#0 14.71 `time="2023-11-02T08:14:37Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 \time="2023-11-02T08:14:37Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 14.71 time="2023-11-02T08:14:37Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 14.71 time="2023-11-02T08:14:37Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 time="2023-11-02T08:14:37Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 
------
http: invalid Host header

`

**Comment by nash-md** [comment]
I tried to install it on a new docker environment on macOS and it worked. Can you share some details what your operating system and docker version is? Are you using the docker desktop? My assumption is it has to do with `containerd` however this is a warning but not a fatal error on your log.

**Comment by nikomaxos** [comment]
i removed everything restarted and reinstalled, everything looks fine, thank you!

**Comment by nikomaxos** [comment]
case closed
