### ISSUE TITLE
needs new Contacts collection and be use it in Accounts

### ISSUE THREAD

**Issue by srinivengala** [nash-md/meow#3]
First of all I love this app. I am using it for job searching.

A new contacts page for selected account.
Able to add multiple contacts to same account.
Choose contact in the opportunity card.

For now I created a text area in Accounts schema to paste all contacts details.
Also in card schema i added text area to paste particular contact from the account.

**Comment by srinivengala** [comment]
nvm, I understood I need to use account for contact details and company name can be a field in the account schema.

learned the hard way now :)

**Comment by nash-md** [comment]
@srinivengala Thanks for the great feedback. I can absolutely understand if there is the need for a separate **contacts** object. Right now this is lean, you would create your contacts on the account, but for sure this only works in use cases where you do not have many contacts, and it's not a relationships at all so in the current situation there are limitations.

If you have feedback for me how you currently use the app and how you would like to store contact details I will check if we can build it.

**Comment by srinivengala** [comment]
Hi,

Thanks for great software. I am new to crm and erp. I have trouble tracking
interviews and applications. So came to know a crm can help.

I initially associated account to a company in my mind. And created a text
area for contact signatures I can paste from email.

There are couple consulting companies, almost 10 people sent emails with
job descriptions. This this text area keeps growing.

I raised issue on meow crm git repo. Later got idea to use name field of
account as <contact name>-<company name>. I added company text box to
account schema. So now account represents one contact and not company.

Started creating new accounts for each contact, duplicating company name.

Since search is case sensitive. I used only lower case letters in name
field. This bit me before as I added duplicate records not knowing entry
already exist.

Now I don't have problem using meow as Iuckily I got the idea to use
contacts at account level.

Can you give me high level process how to add contacts feature.
1. Add contact collection and it's schema in Mongo.
2. Need to be able to add a list of contacts definition to account schema.
3. Figure out font end code for accounts
4. Add contacts page like accounts page

It is cool to see how ui can be configured at runtime. Love the app.
Learned something new about UI development.

Best regards
Srinivas Vengala

**Comment by srinivengala** [comment]
3. Figure out account schema ui to be able to associate multiple contacts

**Comment by srinivengala** [comment]
One more thing I am guessing prediction dashboard will work once I have
something in closed won column right?

**Comment by nash-md** [comment]
Thanks for the Feedback. Just one note, the search should work case insensitive if you search for **"Meow"** it should find a card with **"meow"** as well. If this is not the case for you we should look into it.

So in general an **opportunity** or **card** should be a item you work on with a close date, a follow up date and details. I could imagine in your case the **job** or **applications** could be a match for this. You can then link this **job** to an **account**. Right now this is still basic but the schema editor supports a **Reference** to the account. 

If I think about your use case there is pros and cons to all of this, and I must admit I did not fully understand how you work with your clients. If you like contact me on LinkedIn and then you send me an email with how you work with your clients and I would give you advice.

Forecast:
You have lanes which are included in the forecast, but you can exclude lanes in case they are not relevant. If you go to the forecast screen the **close date** is relevant, to give an example. If you have an opportunity with a close date 7th of December in a lane that is forecasted this amount should show up as **Pipeline - not closed yet** if you select December as your forecast period. A deal that was moved to **Closed Won** would be shown as a closed one deal on the forecast. I hope this helps.

**Comment by srinivengala** [comment]
thanks for the information. My bad I thought its case sensitive. I might
have searched wrong. Glad I can use original casing now.

Now that I added the expected closed date to opportunities, I see forecast
showing predictions now.

[image: image.png]

[image: image.png]
[image: image.png]
[image: image.png]

**Comment by srinivengala** [comment]
I would really like the "save" button next to the close button on top too
for the side panels that popup for accounts and opportunities. This is to
avoid scrolling down everytime I make an update at the top. as I also have
job description pasted in one textarea.

I will see if time permits I can create a pull request.

**Comment by nash-md** [comment]
Yes, that's a good idea, please create a pull request for it. Long-term the plan is to have the close-button left to the card,  like a flag but in the meantime it's good if we move the save button. I will merge your request after you created it.
